name: Snyk Node Security Scan

on:
  push:
    branches: [ "main", "DSSRF_Branch_Rule" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    runs-on: ubuntu-latest  # Required to fix the job failure
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # Pinned to specific SHA

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # Pinned to specific SHA
        with:
          node-version: '20' 
          cache: 'npm'

      - name: Install Dependencies
        # This fixes the SNYK-CLI-0000 "Missing node_modules" error
        run: npm install 
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@e2221410bff24446ba09102212d8bc75a567237d # Pinned to specific SHA
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-results.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@7434149006143a4d75b82a2f411ef15b03ccc2d7 # Pinned to specific SHA
        if: always()
        with:
          sarif_file: snyk-results.sarif
